ALTER TABLE embalagens ADD COLUMN IF NOT EXISTS cobrar BOOLEAN DEFAULT false;
ALTER TABLE embalagens ADD COLUMN IF NOT EXISTS descontar BOOLEAN DEFAULT false;
ALTER TABLE embalagens ADD COLUMN IF NOT EXISTS valor_cobrar NUMERIC(10,2);
ALTER TABLE embalagens ADD COLUMN IF NOT EXISTS valor_descontar NUMERIC(10,2);
